version: '3.9'

services:
    mysql:
        image: mysql:8.1
        container_name: local-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cicipu
            MYSQL_USER: app_user
            MYSQL_PASSWORD: app_user
        volumes:
            - mysql_data:/var/lib/mysql
        restart: unless-stopped

volumes:
    mysql_data:
