export default new Map([
  ['adj', 'adjective'],
  ['adv', 'adverb'],
  ['advp', 'adverbial phrase'],
  ['ag', 'agreement marker (non-verbal)'],
  ['aggen', 'agreement marker in genitive construction'],
  ['agp', 'person subject agreement marker'],
  ['agpi', 'irrealis person subject agreement marker'],
  ['agr', 'agreement marker (non-verbal)'],
  ['agv', 'gender subject agreement marker'],
  ['antic', 'anticausative'],
  ['appl', 'applicative'],
  ['art', 'article'],
  ['asp', 'aspect marker'],
  ['assoc_pl', 'associative plural'],
  ['aux', 'auxiliary verb'],
  ['caus', 'causative infix'],
  ['clause', 'full clause (e.g. inflected verb)'],
  ['cnfct', 'counterfactual'],
  ['comp', 'complementiser'],
  ['conj', 'conjunction'],
  ['cop', 'copula'],
  ['daff', 'determiner prefix'],
  ['dem', 'demonstrative'],
  ['dep', 'dependent clause'],
  ['excl', 'exclamation'],
  ['exist', 'existential predicate'],
  ['gen', 'genitive or associative construction'],
  ['greeting', 'greeting'],
  ['hab', 'habitual'],
  ['habp', 'habitual tone taking prefix into account'],
  ['hon', 'honorific'],
  ['ideo', 'ideophone'],
  ['imp', 'imperative'],
  ['intj', 'interjection'],
  ['ITER', 'iterative'],
  ['lcvzr', 'locativiser'],
  ['loc', 'locative'],
  ['n', 'noun'],
  ['naff', 'nominal affix'],
  ['name:f', 'name (female)'],
  ['name:m', 'name (male)'],
  ['nc', 'noun class prefix'],
  ['ncpro', 'noun class pronoun'],
  ['neg', 'negator'],
  ['nmlz', 'nominaliser'],
  ['nom', 'nominaliser'],
  ['nprop', 'proper noun'],
  ['ntone', 'tone pattern applied to nouns'],
  ['ntonep', 'tone pattern applied to nouns (incl prefix)'],
  ['num', 'numeral'],
  ['numadj', 'numerical adjective'],
  ['part', 'discourse particle'],
  ['perf', 'perfect'],
  ['pl', 'plural'],
  ['plac', 'pluractional infix'],
  ['PP', 'prepositional phrase'],
  ['ppro', 'possessive pronoun'],
  ['prep', 'preposition'],
  ['pres', 'presentative'],
  ['pro', 'pronoun'],
  ['pro cop', 'pronoun followed by copula'],
  ['prohibitive', "prohibitive (i.e. a 'negative' command)"],
  ['quant', 'quantifier'],
  ['question', 'question word'],
  ['rel', 'relativiser'],
  ['reprt', 'reportative evidential'],
  ['res', 'resultative'],
  ['rls', 'realis'],
  ['tns', 'tense marker'],
  ['top', 'topic'],
  ['tone.mark', 'trick'],
  ['v', 'verb'],
  ['vaff', 'verbal affix'],
  ['vcl', 'object clitic'],
  ['vent', 'ventive directional suffix'],
  ['vtone', 'tone pattern applied to verbs'],
  ['vtonep', 'tone pattern applied to verbs (incl prefix)'],
  ['vtone_dv', 'tone pattern applied to the defective verb'],
  ['?trick', 'Ignore - trick for parsing']
])
